### ISSUE TITLE
Integrate with DiffEqBayes.jl

### ISSUE THREAD

**Issue by ChrisRackauckas** [marcjwilliams1/ApproxBayes.jl#19]
https://github.com/JuliaDiffEq/DiffEqBayes.jl is where DiffEq is building a library which integrates with a bunch of Bayesian estimation tools. It would be nice if the same interface that is used to call Stan and Turing.jl inference could be used to call this library.

**Comment by marcjwilliams1** [comment]
I think it should be fairly straightforward to integrate the two. I have a lotka volterra ODE example using DiffEq here: https://github.com/marcjwilliams1/ApproxBayes.jl/blob/master/examples/LV.jl

Would be happy to do this
