### ISSUE TITLE
Parallelize algorithms

### ISSUE THREAD

**Issue by marcjwilliams1** [marcjwilliams1/ApproxBayes.jl#21]
Shouldn't be too hard using julia's parallel features.

**Comment by rdbrackston** [comment]
Hi Marc, I've started working on a parallel implementation using multi-threading. If you're happy with this, I'll submit a pull request once I have things working.

**Comment by marcjwilliams1** [comment]
That would be amazing. Been on my to do list for a while!

**Comment by marcjwilliams1** [comment]
Parallelism available in ABCRejection and ABC-SMC with #34
