### ISSUE TITLE
plotparameterposterior

### ISSUE THREAD

**Issue by Mehdilotfi7** [marcjwilliams1/ApproxBayes.jl#58]
Hi
In LV.jl example, why the command "plotparameterposterior(ressmc)" does not work?
The error is this:
UndefVarError: plotparameterposterior not defined
Stacktrace:
 [1] top-level scope

Which package should I call for that?

**Comment by marcjwilliams1** [comment]
Hi, those examples are very old sorry. You should be able to just use `plot(ressmc)`.
