### ISSUE TITLE
Small question about the LICENSE file

### ISSUE THREAD

**Issue by cralibe** [marcjwilliams1/ApproxBayes.jl#62]
Hi there,

I’ve been exploring ApproxBayes.jl for a project I’m working on and it looks really promising! I noticed that the LICENSE file refers to "The Example.jl package" and just wanted to double-check if it’s licensed under MIT, as I’d like to be sure I’m using it correctly in my work.

I’m really excited about incorporating it into my project and just wanted to clarify that small detail.

Thanks so much for sharing this great package, and looking forward to your reply!

**Comment by cralibe** [comment]
And just to clarify, I want to develop a julia package for ecological analysis which depends on your packpage.

**Comment by marcjwilliams1** [comment]
hi @cralibe, yes license is MIT, I just changed to LICENSE.md file. Thanks and good luck!

**Comment by cralibe** [comment]
Thank you!
